Use Confluent's Librdkafka Package
CDOT-CV/jpo-cvdp pull request #25
Opened 2023-04-11 21:16 UTC by dmccoystephenson

## Changes
Awhile ago we switched over to using Confluent's librdkafka package in the ACM since it was more up to date than the default package provided by ubuntu. These changes make the same switch for the PPM.

## Motivation
Our PPM deployments were disconnecting from kafka intermittently. Using Confluent's librdkafka package seems to resolve this.

## Testing
This has been tested in our dev & test clusters.

2023-04-17 12:53 UTC, payneBrandon commented on Dockerfile
> +RUN apt-get update && apt-get install -y software-properties-common wget git make gcc-7 g++-7 gcc-7-base && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 100 && update-alternatives --
Looks like g++ is repeated here now.

2023-04-17 12:56 UTC, payneBrandon requested changes
Just the one comment

2023-04-19 13:16 UTC, payneBrandon approved these changes
Looks good to me!

2023-04-25 20:30 UTC, drewjj approved these changes
Yeah, this looks good

2023-04-25 20:31 UTC, merged